import type { Metadata } from "next";
import "./globals.css";
import { clashDisplay } from "@/app/utils/font";

export const metadata: Metadata = {
  title: "VIE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${clashDisplay.variable} antialiased overflow-x-hidden`}
      >
        <div className="">
          {children}
        </div>
      </body>
    </html>
  );
}