import type { Metadata } from "next";
import "./globals.css";
import Layout from "./component/Layout";
import { creatoDisplay, metapro } from "./utils/font";

export const metadata: Metadata = {
  title: "VIE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${creatoDisplay.variable} ${metapro.variable}  antialiased overflow-x-hidden`}
      >
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
