import type { Metadata } from "next";
import "./globals.css";
import Header from "./component/Header";
import Footer from "./component/Footer";
import { clashDisplay } from "./utils/font";

export const metadata: Metadata = {
  title: "VIE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${clashDisplay.variable} antialiased overflow-x-hidden`}
      >
        <div className="bg-[#FBFBFB]">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
